# Example: Simplified G16 configuration using the new architecture
# G16 is an ASUS gaming laptop
{ ... }:

{
  imports = [
    # Import the gaming workstation profile
    ../modules/profiles/gaming-workstation.nix
    
    # Hardware-specific configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix
  ];

  # Set hostname and user
  networking.hostName = "G16";
  maxos.user.name = "user";

  # Enable hardware optimizations for gaming laptop
  maxos.hardware.laptop = {
    enable = true;
    powerManagement.enable = true;  # Important for battery life
    powerManagement.tlp = true;     # Advanced power management
    display.backlight = true;       # Backlight control
    touchpad.enable = true;
    wireless.enable = true;
    wireless.bluetooth = true;
  };

  # Additional desktop-class performance when plugged in
  maxos.hardware.desktop = {
    graphics.enable = true;
    graphics.nvidia = true;  # ASUS G16 has NVIDIA GPU
    audio.enable = true;
    audio.lowLatency = true; # For content creation/streaming
  };

  # Use the content-creator pattern (combines gaming + streaming)
  modules.toolBundles.usagePatterns = {
    enable = true;
    preset = "content-creator";
    
    # Customizations specific to G16 laptop
    customizations = {
      # Enhanced AI capabilities
      aiMl.profile = "developer";
      aiMl.enableWebInterface = true;
      
      # Full development stack
      webdev.profile = "fullstack";
      
      # Gaming optimizations
      gaming.profile = "enthusiast";
      gaming.enableRecording = true;
      
      # Laptop-specific power considerations
      hardware.laptop.powerManagement.tlp = true;
    };
  };

  # G16-specific tool overrides
  modules.tools = {
    # Gaming and content creation
    steam.enable = true;
    simplescreenrecorder.enable = true;
    
    # AI tools
    ollama.enable = true;
    open-webui.enable = true;
    
    # Development tools
    docker.enable = true;
    chromium.enable = true;
    keepassxc.enable = true;
  };

  # Laptop-specific power management
  powerManagement = {
    enable = true;
    powertop.enable = true;
  };

  # Gaming laptop specific services
  services = {
    # ASUS ROG specific
    supergfxd.enable = true;  # GPU switching for battery life
    power-profiles-daemon.enable = false; # Use TLP instead
  };

  # System state version
  system.stateVersion = "25.11";
}

# This configuration recognizes G16 as a high-performance gaming laptop
# with both gaming capabilities and power management for mobility