{ config, pkgs, lib, ... }:

# ASUS G16 Gaming Laptop Configuration
# Simplified using MaxOS profiles and hardware abstractions

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./users.nix
    ./boot.nix
    ./nvidia.nix
    ./rog.nix
    ./audio.nix
    ./power.nix
    
    # MaxOS gaming workstation profile
    ../../modules/profiles/gaming-workstation.nix
  ];

  # Basic system identification
  networking.hostName = "G16";
  
  # User configuration
  maxos.user = {
    name = "user";
    homeDirectory = "/home/user";
    gitDirectory = "/home/user/git";
    monorepoDirectory = "/home/user/git/github/monorepo";
    secretsDirectory = "/home/user/git/github/monorepo/secrets";
    workspaceDirectory = "/home/user/monorepo/tools/goose/workspace";
  };

  # Hardware profile for ASUS G16 gaming laptop
  maxos.hardware.laptop = {
    enable = true;
    powerManagement.enable = true;
    powerManagement.tlp = true;
    display.backlight = true;
    display.autoSuspend = true;
    touchpad = {
      enable = true;
      naturalScrolling = false;
    };
    wireless = {
      enable = true;
      bluetooth = true;
    };
  };

  # Desktop-class graphics and audio for gaming
  maxos.hardware.desktop = {
    graphics = {
      enable = true;
      nvidia = true;
    };
    audio = {
      enable = true;
      lowLatency = true;  # For content creation
    };
  };

  # Use content creator usage pattern (gaming + streaming + development)
  modules.toolBundles.usagePatterns = {
    enable = true;
    preset = "content-creator";
    
    customizations = {
      # AI development tools
      aiMl.profile = "developer";
      aiMl.enableWebInterface = false;  # Disabled for now
      
      # Development capabilities
      webdev.enable = false;  # Disabled for now
      kubernetes.enable = false;  # Disabled for now
      
      # Enhanced gaming and content creation
      gaming.profile = "enthusiast";
      contentCreation.profile = "streamer";
    };
  };

  # G16-specific tool configuration
  modules.tools = {
    # AI tools (selective enabling)
    ollama.enable = false;
    open-webui.enable = false;
    anythingllm = {
      enable = true;
      port = 3001;
    };
    
    # Content creation and gaming
    simplescreenrecorder.enable = true;
    steam.enable = true;
    
    # Development essentials
    docker.enable = true;
    chromium.enable = true;
    keepassxc.enable = true;
    
    # Backup (disabled - no secrets configured yet)
    restic = {
      enable = false;
      hostSubdir = "G16";
      useSopsSecrets = false;
    };
  };

  # Secrets management (disabled until configured)
  maxos.secrets.enable = false;

  # Security configuration
  security = {
    enable = true;
    authorizedKeys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjMXN/z0u4Sf/+ODpG49ZFBNHqcZFxNgFhTts1GAJrr user@nixos"
    ];
  };

  # G16-specific system configuration
  services = {
    # X11 and i3 (from gaming-workstation profile, but customized)
    xserver = {
      xkb = {
        layout = "gb";
        variant = "dvorakukp";
        options = "terminate:ctrl_alt_bksp";
      };
      displayManager.lightdm = {
        background = "#000000";
        greeters.gtk.theme.name = "Adwaita-dark";
      };
    };
    
    # PAM for i3lock
    pam.services.i3lock.enable = true;
    
    # Disable conflicting services
    redshift.enable = false;
  };

  # Networking
  networking.hosts = {
    "127.0.0.1" = [ "management-api.fisheye.local" "auth-service.fisheye.local" ];
  };

  # K3s registry configuration
  environment.etc."rancher/k3s/registries.yaml".text = ''
    configs:
      "registry.localhost":
        tls:
          insecure_skip_verify: true
  '';

  # Swap configuration
  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024; # 16GB
  }];

  # System configuration
  nixpkgs.config.allowUnfree = true;
  system.stateVersion = "25.05";
}

# This configuration is ~80% smaller than the original while maintaining
# all functionality through the gaming-workstation profile and hardware abstractions