{ config, pkgs, lib, ... }:

# ASUS G16 Gaming Laptop Configuration
# Simplified using MaxOS profiles and hardware abstractions

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./users.nix
    ./boot.nix
    ./nvidia.nix
    ./rog.nix
    ./audio.nix
    ./power.nix
    
    # Note: Now using comprehensive workstation profile instead of gaming-workstation
  ];

  # Basic system identification
  networking.hostName = "G16";
  
  # Enable centralized font management
  maxos.fonts.enable = true;
  
  # User configuration
  maxos.user = {
    name = "user";
    homeDirectory = "/home/user";
    gitDirectory = "/home/user/git";
    monorepoDirectory = "/home/user/git/github/synlace/monorepo";
    secretsDirectory = "/home/user/git/github/synlace/monorepo/secrets";
    workspaceDirectory = "/home/user/monorepo/tools/goose/workspace";
  };

  # Hardware profile for ASUS G16 gaming laptop
  maxos.hardware.laptop = {
    enable = true;
    powerManagement.enable = true;
    powerManagement.tlp = true;
    display.backlight = true;
    display.autoSuspend = true;
    touchpad = {
      enable = true;
      naturalScrolling = false;
    };
    wireless = {
      enable = true;
      bluetooth = true;
    };
  };

  # Desktop-class graphics and audio for gaming
  maxos.hardware.desktop = {
    graphics = {
      enable = true;
      nvidia = true;
    };
    audio = {
      enable = true;
      lowLatency = true;  # For content creation
    };
  };

  # Use comprehensive workstation profile (same as rig)
  maxos.profiles.comprehensiveWorkstation = {
    enable = true;
    profile = "full";  # full profile includes all tools and capabilities
    enableDevelopment = true;
    enableGaming = true;
    enableSecurity = true;
    enableMultimedia = true;
    enableInfrastructure = false;  # Disable k3s infrastructure for G16
  };

  # Enable core system utilities (includes envsubst)
  maxos.tools.system-utilities.enable = true;

  # Secrets management — set enable = true once SOPS age key is initialised.
  # Run `maxos-secrets-init` to generate the age key, then encrypt secrets with:
  #   sops secrets/hosts/G16/secrets.yaml
  # Required keys: anthropic_api_key, openai_api_key
  maxos.secrets = {
    enable = false;
    age.generateKey = false;
    defaultSopsFile = "${config.maxos.user.secretsDirectory}/hosts/G16/secrets.yaml";
  };

  # SOPS secret declarations for OpenClaw API keys.
  # These are only active when maxos.secrets.enable = true (sops-nix is configured).
  # The decrypted values are written to /run/secrets/ at boot.
  sops.secrets = lib.mkIf false {
    # Set lib.mkIf condition to `config.maxos.secrets.enable` to activate.
    anthropic_api_key = {
      sopsFile = "${config.maxos.user.secretsDirectory}/hosts/G16/secrets.yaml";
      owner = config.maxos.user.name;
      mode = "0400";
    };
    openai_api_key = {
      sopsFile = "${config.maxos.user.secretsDirectory}/hosts/G16/secrets.yaml";
      owner = config.maxos.user.name;
      mode = "0400";
    };
  };

  # Security configuration
  security = {
    enable = true;
    authorizedKeys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjMXN/z0u4Sf/+ODpG49ZFBNHqcZFxNgFhTts1GAJrr user@nixos"
    ];
  };

  # G16-specific overrides
  maxos.tools = {
    # Enable Rust Token Killer
    rtk.enable = true;
    
    # Enable OpenCode CLI
    opencode.enable = true;
    
    # Disable blocky to fix WireGuard DNS resolution
    blocky.enable = lib.mkForce false;
    
    # Enable screenshot tools (maim and scrot) for screenshot script
    screenshot-tools.enable = true;

    # Enable asciinema terminal recorder and agg
    asciinema.enable = true;
    
    # Enable pandoc for document conversion
    pandoc.enable = true;
    pandoc.includeExtensions = true;
    
    # Enable just command runner
    just.enable = true;

    # Enable SQLite database engine
    sqlite.enable = true;
    
    # Enable bun JavaScript runtime
    bun.enable = true;

    # Enable Deno JavaScript/TypeScript runtime
    deno.enable = true;

    # Enable watchexec for file watching
    watchexec.enable = true;

    # Enable Android Studio
    android-studio.enable = true;

    # Enable Playwright
    playwright.enable = true;

    # Enable web-ext Mozilla extension CLI tool
    web-ext.enable = true;

    # Enable Python 3
    python3.enable = true;
    
    # Enable OpenAI Codex CLI tool
    codex.enable = true;

    # Enable Wireshark for network analysis
    wireshark.enable = true;
    
    # Enable mitmproxy for interactive HTTPS proxying
    mitmproxy.enable = true;
    
    # Disable Kubernetes tooling
    helmfile.enable = lib.mkForce false;
    aws-cli = {
      enable = true;
      enableSessionManager = true;
    };
    google-cloud-sdk.enable = true;
    stripe-cli.enable = true;
    supabase-cli.enable = true;
    karate.enable = true;
    k3s.enable = lib.mkForce false;
    argocd.enable = lib.mkForce false;
    terraform.enable = lib.mkForce false;
    
    # Enable iSCSI storage support
    open-iscsi.enable = true;
    
    # Enable OpenVPN client
    openvpn.enable = true;

    # Enable WireGuard VPN tools
    wireguard.enable = true;

    # Enable SSHFS for remote filesystem mounting
    sshfs.enable = true;
    
    # Enable AutoSSH for persistent SSH tunnels
    autossh.enable = true;
    
    # Enable Firecracker microVM virtualization
    firecracker = {
      enable = true;
      includeFirectl = true;
    };
    
    # Enable Redis for development and caching
    redis = {
      enable = false;
      maxMemory = "512mb";
      maxMemoryPolicy = "allkeys-lru";
      appendOnly = true;
      logLevel = "notice";
      redisInsight = {
        enable = false;
        port = 8001;
        host = "127.0.0.1";
      };
    };
    
    # Enable MongoDB CE for document database development
    mongodb-ce = {
      enable = false;
      port = 27017;
      bind = "127.0.0.1";
      enableAuth = false;  # Disabled for local development
      storageEngine = "wiredTiger";
      journaling = true;
      logLevel = "normal";
      cacheSizeGB = 1;  # 1GB cache for laptop (smaller than desktop)
      databases = [ "development" "testing" ];
    };
    
    # Disable ollama on G16
    ollama.enable = lib.mkForce false;
    open-webui.enable = lib.mkForce false;
    
    # Disable llama-cpp on G16
    llama-cpp.enable = lib.mkForce false;

    # Disable vLLM - flashinfer dependency is marked broken in current nixpkgs
    vllm.enable = lib.mkForce false;

    # Enable dig for DNS troubleshooting
    dig.enable = true;

    # Enable GNU Screen terminal multiplexer
    screen.enable = true;

    # Enable Knot DNS for authoritative DNS testing
    knot-dns.enable = true;

    # Enable FileZilla FTP client
    filezilla.enable = true;

    # Enable input-leap for KVM software
    input-leap.enable = true;
  };

  # Enable Prowlarr, Sonarr and qBittorrent
  maxos.services.prowlarr.enable = true;
  maxos.services.sonarr.enable = true;
  maxos.services.qbittorrent.enable = true;

  # G16-specific system configuration
  services = {
    # X11 and i3 (from gaming-workstation profile, but customized)
    xserver = {
      xkb = {
        layout = "gb";
        variant = "dvorakukp";
        options = "terminate:ctrl_alt_bksp";
      };
      displayManager.lightdm = {
        background = "#000000";
        greeters.gtk.theme.name = "Adwaita-dark";
      };
    };
    
    # Disable conflicting services
    redshift.enable = false;
  };
  
  # Display manager session and autologin configuration
  services.displayManager = {
    defaultSession = "none+i3";
    autoLogin = {
      enable = true;
      user = "user";
    };
  };
  
  # PAM for i3lock
  security.pam.services.i3lock = {};
  
  # Enable zsh since user shell is set to zsh
  programs.zsh.enable = true;

  # Networking - K3s disabled, no static IP needed
  
  # Disable automatic /etc/hosts generation
  environment.etc.hosts.enable = false;

  # Swap configuration
  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024; # 16GB
  }];

  # Additional system packages
  environment.systemPackages = with pkgs; [
    postgresql # PostgreSQL client tools (psql, pg_dump, etc.)
    gcc        # GNU Compiler Collection
    pkg-config # Package config tool
    devbox     # Isolated development environments tool
  ];

  # Mount Storage Box via SSHFS
  fileSystems."/home/user/media" = {
    device = "u531385@u531385.your-storagebox.de:/";
    fsType = "fuse.sshfs";
    options = [
      "allow_other"
      "uid=1000"
      "gid=100"
      "idmap=user"
      "IdentityFile=/home/user/.ssh/id_ed25519"
      "ssh_command=${pkgs.openssh}/bin/ssh"
      "StrictHostKeyChecking=no"
      "UserKnownHostsFile=/dev/null"
      "x-systemd.automount"
      "_netdev"
      "reconnect"
      "ServerAliveInterval=15"
      "ServerAliveCountMax=3"
      "delay_connect"
    ];
  };

  # System configuration
  nixpkgs.config.allowUnfree = true;
  system.stateVersion = "25.11";
}

# This configuration is ~80% smaller than the original while maintaining
# all functionality through the gaming-workstation profile and hardware abstractions
