{ config, pkgs, lib, ... }:

with lib;

let
  cfg = config.maxos.tools.blocky;
in
{
  options.maxos.tools.blocky = {
    enable = mkEnableOption "Blocky DNS";
  };

  config = mkIf cfg.enable {
    # Temporarily disable Blocky service
    services.blocky.enable = false;
    
    # Use Google DNS directly instead of Blocky
    networking.nameservers = [ "8.8.8.8" "8.8.4.4" "1.1.1.1" ];
    
    # Enable systemd-resolved for better container DNS support
    # Note: This conflicts with the kind.nix configuration, but kind.nix takes precedence
    services.resolved.enable = lib.mkDefault false;
    
    # Configure DNS for container compatibility
    environment.etc."systemd/resolved.conf.d/container-dns.conf".text = ''
      [Resolve]
      DNS=8.8.8.8 8.8.4.4 1.1.1.1
      FallbackDNS=8.8.8.8 8.8.4.4
      Domains=~.
      DNSSEC=false
      DNSOverTLS=false
      MulticastDNS=false
      LLMNR=false
      Cache=true
      DNSStubListener=true
      ReadEtcHosts=true
    '';
    
    # Ensure proper DNS resolution in /etc/resolv.conf for containers
    environment.etc."resolv.conf".text = lib.mkForce ''
      # Generated by NixOS for container compatibility
      nameserver 8.8.8.8
      nameserver 8.8.4.4
      nameserver 1.1.1.1
      options ndots:2 timeout:3 attempts:2
      search default.svc.cluster.local svc.cluster.local cluster.local
    '';
  };
}